### ISSUE TITLE
Patch: AWS AMI customization

### ISSUE THREAD

**Issue by dkoshkin** [d2iq-labs/capi-runtime-extensions#199]
Add a patch to set AMI information that will then set AWS's API https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/1fb82d9f556c0d840bafa519f63407cac8de2b9b/exp/api/v1beta2/types.go#L67-L90

Here is a proposed API:
```
value:
  aws:
    ami:
      id: <optional>
      lookup:
        format: "capa-ami-{{.BaseOS}}-?{{.K8sVersion}}-*"
        org: "258751437250"
        format: "ubuntu-20.04"
```
