### ISSUE TITLE
Patch: AWS Subnet IDs

### ISSUE THREAD

**Issue by dkoshkin** [d2iq-labs/capi-runtime-extensions#200]
Add a patch to set existing Subnets to use https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/1fb82d9f556c0d840bafa519f63407cac8de2b9b/api/v1beta1/network_types.go#L154-L156

Here is a proposed API:
```
values:
  aws:
    network:
      subnets:
      - id:
      ...
```

Needed to support creating clusters in existing air-gapped infrastructure.
