### ISSUE TITLE
Patch: AWS VPC ID

### ISSUE THREAD

**Issue by dkoshkin** [d2iq-labs/capi-runtime-extensions#201]
Add a patch to set existing VPC to use https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/1fb82d9f556c0d840bafa519f63407cac8de2b9b/api/v1beta1/network_types.go#L150-L152

Here is a proposed API:
```
values:
  aws:
    network:
      vpc:
        id:
```

Needed to support creating clusters in existing air-gapped infrastructure.
