### ISSUE TITLE
Patch: AWS LoadBalancer scheme

### ISSUE THREAD

**Issue by dkoshkin** [d2iq-labs/capi-runtime-extensions#202]
Add a patch to set the scheme to use for the control-plane Server LoadBalancer - https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/1fb82d9f556c0d840bafa519f63407cac8de2b9b/api/v1beta2/awscluster_types.go#L183

Here is a proposed API:
```
values:
  aws:
    controlPlaneLoadBalancer:
      scheme: *ClassicELBScheme (from CAPA API package)
```

Needed to support creating clusters in existing air-gapped infrastructure.
