### ISSUE TITLE
Patch: Generic Containerd mirror support

### ISSUE THREAD

**Issue by dkoshkin** [d2iq-labs/capi-runtime-extensions#203]
Extend the [image registries API](https://github.com/d2iq-labs/capi-runtime-extensions/blob/main/docs/content/customization/generic/image-registries.md) to also enable [Containerd mirror](https://github.com/containerd/containerd/blob/main/docs/hosts.md#setup-default-mirror-for-all-registries).

```yaml
spec:
  topology:
    variables:
      - name: clusterConfig
        value:
          imageRegistries:
            credentials: 
              - url: https://my-registry.io
                secretRef:
                    name: <optional ref to a Secret that holds the credentials>
                mirror:
                    caSecretRef:
                      name: <optional ref to a Secret that holds a self signed CA>   
```

A an image registry can either be configured to pass credentials (already implemented), a Containerd mirror or both.

1. Just a Containerd mirror, see [here](https://github.com/containerd/containerd/blob/main/docs/hosts.md#setup-default-mirror-for-all-registries). Note how the `server` is removed since we want to still fallback to upstream registry if image not found in the mirror:
```
$ tree /etc/containerd/certs.d
/etc/containerd/certs.d
└── _default
    └── hosts.toml

$ cat /etc/containerd/certs.d/_default/hosts.toml

[host."https://my-registry.io"]
  capabilities = ["pull", "resolve"]
```

2. Both a Containerd mirror and credentials provider:
Configure same as above for 1 and after [here](https://github.com/d2iq-labs/capi-runtime-extensions/blob/5ea3c1e0dc60c7e428ae34f53a5fbb596eccaeef/pkg/handlers/generic/mutation/imageregistries/credentials/templates/dynamic-credential-provider-config.yaml.gotmpl#L3) add

```
          mirror:
            endpoint: "my-registry.io"
            credentialsStrategy: MirrorCredentialsOnly
```

Pay special attention to the format the URL is expected in, e.g. with port, with path, etc.
