### ISSUE TITLE
Patch: AWS additionalSecurityGroups

### ISSUE THREAD

**Issue by dkoshkin** [d2iq-labs/capi-runtime-extensions#230]
Add [AWS additionalSecurityGroups configuration](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/2b25bdd100ce215eb46ef6d72dfa9dec7014d5ef/api/v1beta2/awsmachine_types.go#L105-L110C57) AWSMachineTemplates:

```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: <NAME>
spec:
  topology:
    variables:
      - name: clusterConfig
        value:
          controlPlane:
            aws:
              additionalSecurityGroups:
                - sg-1
                - sg-2
      - name: workerConfig
        value:
          aws:
            additionalSecurityGroups:
              - sg-1
              - sg-2
```
