### ISSUE TITLE
Support for mirror credentials for "globalImageRegistryMirror"

### ISSUE THREAD

**Issue by supershal** [d2iq-labs/capi-runtime-extensions#329]
The secret provided for globalImageRegistry currently only reads "ca.crt" key.  
```
 globalImageRegistryMirror:
            url: https://my-mirror.io
            credentials:
              secretRef:
                name: my-mirror-ca-cert
```
Enable support for static credentials by reading `username` and `password` keys and creating Dynamic Credentials provider configuration for mirror. 

create Dynamic Credentials provider config to add credentialsStrategy
```
mirror:
            endpoint: "my-registry.io"
            credentialsStrategy: MirrorCredentialsOnly
```
Update existing Dynamic credentials provider/create new to add static credentials for mirror.
